name: CI/CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build \
            -t klinik-aagaard:${{ github.sha }} \
            -t klinik-aagaard:latest \
            .

      - name: Deploy
        run: ~/scripts/deploy.sh klinik-aagaard
